// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/web-design": {
    params: {};
  };
  "/app-design": {
    params: {};
  };
  "/graphic-design": {
    params: {};
  };
  "/company": {
    params: {};
  };
  "/locations": {
    params: {};
  };
  "/contact": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/web-design" | "/app-design" | "/graphic-design" | "/company" | "/locations" | "/contact";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/WebDesign.tsx": {
    id: "routes/WebDesign";
    page: "/web-design";
  };
  "routes/AppDesign.tsx": {
    id: "routes/AppDesign";
    page: "/app-design";
  };
  "routes/GraphicDesign.tsx": {
    id: "routes/GraphicDesign";
    page: "/graphic-design";
  };
  "routes/AboutUs.tsx": {
    id: "routes/AboutUs";
    page: "/company";
  };
  "routes/Locations.tsx": {
    id: "routes/Locations";
    page: "/locations";
  };
  "routes/Contact.tsx": {
    id: "routes/Contact";
    page: "/contact";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/WebDesign": typeof import("./app/routes/WebDesign.tsx");
  "routes/AppDesign": typeof import("./app/routes/AppDesign.tsx");
  "routes/GraphicDesign": typeof import("./app/routes/GraphicDesign.tsx");
  "routes/AboutUs": typeof import("./app/routes/AboutUs.tsx");
  "routes/Locations": typeof import("./app/routes/Locations.tsx");
  "routes/Contact": typeof import("./app/routes/Contact.tsx");
};