// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/web-design": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/web-design";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/webDesign.tsx": {
    id: "routes/webDesign";
    page: "/web-design";
  };
};